// qiankun-demo/react-app/src/App.js
import { useState } from 'react';
import './App.css';

function App({ actions }) {
  const [count, setCount] = useState(0);

  const changeUser = () => {
    const nextCount = count + 1;
    setCount(nextCount);
    actions?.setGlobalState({
      globalMessage: {
        from: 'react-app',
        count: nextCount,
        timestamp: Date.now()
      }
    });
  };

  return (
    <div className='App'>
      <button onClick={changeUser}>Click {count}</button>
    </div>
  );
}

export default App;

// qiankun-demo/vue2-app/src/App.vue
<template>
  <div id="app">
    <button @click="openLoading">Trigger global loading</button>
  </div>
</template>

<script>
export default {
  methods: {
    openLoading() {
      const actions = this.$globalActions;
      actions?.setGlobalState({ loading: true });
      actions?.setGlobalState({
        vue2ToVue3: {
          msg: 'hello vue3 from vue2',
          timestamp: Date.now()
        }
      });
    }
  }
};
</script>
